g09rt: myg09boon
g09a2rt: myg09a2boon

antechamber: antechamber -c resp
clean: rm *gaussian*


opthead: |
  %mem=16gb
  %nproc=12
  #p b3lyp/6-31+g* geom=connectivity
  int=ultrafine symm=(loose,follow)
  opt=(verytight,maxstep=7,notrust)

  opt-title


opttail: |


freqhead: |
  %mem=16gb
  %nproc=12
  #p b3lyp/chkbas int=ultrafine symm=loose geom=allcheck guess=tcheck freq=intmodes iop(7/33=1)


resphead: |
  %mem=16gb
  %nproc=12
  #p b3lyp/chkbas
  iop(6/33=2,6/42=17,6/41=10)
  int=ultrafine symm=loose
  pop=mk
  geom=allcheck guess=tcheck


resptail: |


mmhead: |
  %mem=12gb
  #p amber=softonly geom=connectivity nosymm
  iop(4/33=3,7/33=1)
  freq=intmodes

  MM


